version: '3.9'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo:/data/db
    ports:
      - '6000:27017'

  backend:
    restart: always
    build:
      context: ./app
    ports:
      - "8000:8000"
    command: bash -c 'uvicorn app.main:app --reload'
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  mongo:
